### ISSUE TITLE
Question: how to use it for boosting the result instead of qparser filtering it?

### ISSUE THREAD

**Issue by megastef** [sematext/query-segmenter#1]

**Comment by xs0358** [comment]
Thanks for posting the question. If it is possible, adding the segmenter to the bq will be a nice to have feature. Can we do it through edismax bq?

**Comment by nmtien** [comment]
Currently it is not possible to boost in that way, but that is nice feature and we will add it when we have time. Any patch are welcome.

**Comment by the-xs** [comment]
@nmtien: Code is forked and feature is added. Let me know if you would like a PR.

**Comment by otisg** [comment]
Yes please, @the-xs !

**Comment by georgms** [comment]
@the-xs Any news on the PR? I think that's a great idea!

**Comment by the-xs** [comment]
@georgms Working on to finalize it.

**Comment by nmtien** [comment]
Added by https://github.com/sematext/query-segmenter/pull/5
